// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mB4p60QcBw6QavmD23_hWA9rsC6DcdM',
    appId: '1:3495783133:web:b669f59eebb7d6369fc934',
    messagingSenderId: '3495783133',
    projectId: 'fir-basic-969f8',
    authDomain: 'fir-basic-969f8.firebaseapp.com',
    storageBucket: 'fir-basic-969f8.firebasestorage.app',
    measurementId: 'G-9DBZ3GQTRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQBPvFFaj1bmzDbmlGgCgUQtjGs5wvSXk',
    appId: '1:3495783133:android:617ce0d95ee023379fc934',
    messagingSenderId: '3495783133',
    projectId: 'fir-basic-969f8',
    storageBucket: 'fir-basic-969f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Ig9eDHZnAeIJRzmgxMlRWGAkTkYkf1A',
    appId: '1:3495783133:ios:0fdc4cb10e18016f9fc934',
    messagingSenderId: '3495783133',
    projectId: 'fir-basic-969f8',
    storageBucket: 'fir-basic-969f8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Ig9eDHZnAeIJRzmgxMlRWGAkTkYkf1A',
    appId: '1:3495783133:ios:0fdc4cb10e18016f9fc934',
    messagingSenderId: '3495783133',
    projectId: 'fir-basic-969f8',
    storageBucket: 'fir-basic-969f8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseBasic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2mB4p60QcBw6QavmD23_hWA9rsC6DcdM',
    appId: '1:3495783133:web:802bd7af0c368a679fc934',
    messagingSenderId: '3495783133',
    projectId: 'fir-basic-969f8',
    authDomain: 'fir-basic-969f8.firebaseapp.com',
    storageBucket: 'fir-basic-969f8.firebasestorage.app',
    measurementId: 'G-29VPVGJWZM',
  );
}
